version: "3.9"

services:
    db:
        image: mongo:latest
        ports: 
            - 27017:27017
        restart: always
        volumes:
            - ./db_init.js:/docker-entrypoint-initdb.d/db_init.js

    app:
        depends_on: 
            - db
        build: .
        ports: 
            - 50051:50051
        restart: always