version: "3.9"

services:
    db:
        image: mongo:latest
        ports: 
            - "27017:27017"
        restart: always
        volumes:
            - ./db_init.js:/docker-entrypoint-initdb.d/db_init.js

    app:
        depends_on: 
            - db
        build: .
        ports: 
            - "9999:9999"
            - "50051:50051"
        restart: always

    prometheus:
        image: prom/prometheus:latest
        depends_on:
            - app
        ports:
            - "9090:9090"
        volumes:
            - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    grafana:
        image: grafana/grafana:latest
        ports: 
            - "3000:3000"
        volumes:
            - ./grafana:/etc/grafana/provisioning

#            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
#            - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
#            - ./grafana/dash.json:/etc/grafana/provisioning/dashboards/dash.json
