<<<<<<< HEAD
version: "3.9"

services:
    db:
        image: mongo:latest
        ports: 
            - 27017:27017
        restart: always
        volumes:
            - ./db_init.js:/docker-entrypoint-initdb.d/db_init.js

    app:
        depends_on: 
            - db
        build: .
        ports: 
            - 50051:50051
        restart: always
=======
version: "3.8"
services:
        build: 
            context: .
            dockerfile: Dockerfile
        image: server
        ports:
            - "50051:50051"
    web:
        build:
            context: .
            dockerfile: client.Dockerfile
        image: snake/client
        ports:
            - "8081:80"
>>>>>>> 572d0581ca5d690acc5803a8114828bb87d13174
