version: "3.8"
services:
        build: 
            context: .
            dockerfile: Dockerfile
        image: server
        ports:
            - "50051:50051"
    web:
        build:
            context: .
            dockerfile: client.Dockerfile
        image: snake/client
        ports:
            - "8081:80"